# Generated by Django 3.1.1 on 2025-07-29 14:33

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
